const modules = ['capital','purchases','sales','stock','expenses','debts','crops'];
let currentPage = 'dashboard';
const money = n => new Intl.NumberFormat('sw-TZ').format(Number(n||0)) + ' TSh';
const today = new Date().toLocaleDateString('sw-TZ',{weekday:'long',year:'numeric',month:'long',day:'numeric'});
document.getElementById('today').textContent = today;
function q(s){return document.querySelector(s)} function qa(s){return [...document.querySelectorAll(s)]}
async function refreshDashboard(){ const d = await window.nassAPI.getDashboard(); q('#dCapital').textContent=money(d.capital); q('#dSales').textContent=money(d.sales); q('#dCosts').textContent=money(d.purchases+d.expenses); q('#dProfit').textContent=money(d.profit); q('#scoreBar').style.width=d.disciplineScore+'%'; q('#scoreText').textContent=`${d.disciplineScore}/100 - ${d.disciplineScore>=70?'Nidhamu yako ya fedha iko vizuri.':'Punguza matumizi yasiyo ya lazima ili mtaji ukue.'}`; }
function setupNav(){ qa('.nav').forEach(btn=>btn.onclick=()=>{ qa('.nav').forEach(b=>b.classList.remove('active')); qa('.page').forEach(p=>p.classList.remove('active')); btn.classList.add('active'); currentPage=btn.dataset.page; q('#'+currentPage).classList.add('active'); q('#pageTitle').textContent=btn.textContent; if(modules.includes(currentPage)) renderModule(currentPage); if(currentPage==='dashboard') refreshDashboard(); }); }
function setupCrud(){ modules.forEach(module=>{ const el=q(`[data-module="${module}"]`); el.insertAdjacentHTML('beforeend', `<div class="form"><input data-f="date" type="date"><input data-f="name" placeholder="Jina/Maelezo"><input data-f="crop" placeholder="Zao"><input data-f="quantity" type="number" placeholder="Kiasi"><input data-f="unit" placeholder="Unit"><input data-f="amount" type="number" placeholder="Fedha"><button class="add">Ongeza</button></div><div id="table-${module}"></div>`); el.querySelector('.add').onclick=async()=>{ const record={module}; el.querySelectorAll('[data-f]').forEach(i=>record[i.dataset.f]=i.value); if(!record.date) record.date=new Date().toISOString().slice(0,10); await window.nassAPI.addRecord(record); el.querySelectorAll('[data-f]').forEach(i=>i.value=''); await renderModule(module); await refreshDashboard(); }; }); }
async function renderModule(module){ const rows=await window.nassAPI.listRecords(module); const wrap=q(`#table-${module}`); if(!rows.length){ wrap.innerHTML='<div class="empty">Hakuna taarifa bado.</div>'; return; } wrap.innerHTML=`<table><thead><tr><th>Tarehe</th><th>Maelezo</th><th>Zao</th><th>Kiasi</th><th>Unit</th><th>Fedha</th><th>Vitendo</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date||''}</td><td>${r.name||''}</td><td>${r.crop||''}</td><td>${r.quantity||''}</td><td>${r.unit||''}</td><td>${money(r.amount)}</td><td><button class="small" onclick="editRow('${r.id}','${module}','${String(r.name||'').replaceAll("'","&#39;")}',${Number(r.amount||0)})">Badili</button><button class="small danger" onclick="deleteRow('${r.id}','${module}')">Futa</button></td></tr>`).join('')}</tbody></table>`; }
window.deleteRow=async(id,module)=>{ if(confirm('Una uhakika unataka kufuta taarifa hii?')){ await window.nassAPI.deleteRecord(id); await renderModule(module); await refreshDashboard(); }};
window.editRow=async(id,module,name,amount)=>{ const n=prompt('Badili maelezo:',name); if(n===null)return; const a=prompt('Badili kiasi cha fedha:',amount); if(a===null)return; await window.nassAPI.updateRecord(id,{name:n,amount:Number(a||0)}); await renderModule(module); await refreshDashboard(); };
function setupTop(){ q('#backupBtn').onclick=async()=>alert('Backup imehifadhiwa:\n'+await window.nassAPI.createBackup('manual')); q('#formatBtn').onclick=async()=>{ if(await window.nassAPI.formatData()){ await refreshDashboard(); if(modules.includes(currentPage)) await renderModule(currentPage); }}; q('#langBtn').onclick=()=>alert('Mfumo wa lugha mbili umeandaliwa. UI kamili ya English itaongezwa kupitia update inayofuata bila kufuta data.'); q('#listBackups').onclick=async()=>{ const rows=await window.nassAPI.listBackups(); q('#backupList').textContent=rows.map(x=>`${x.created} - ${x.name}`).join('\n') || 'Hakuna backup bado.'; }; }
function setupUpdates(){ const st=q('#updateStatus'); q('#checkUpdate').onclick=async()=>{ st.textContent='Inaangalia update...'; const r=await window.nassAPI.checkUpdates(); st.textContent=r.ok?'Imeangalia updates. Kama ipo, utaona taarifa.':'Hitilafu: '+r.error; }; q('#downloadUpdate').onclick=async()=>{ st.textContent='Inapakua update na kutengeneza backup kwanza...'; const r=await window.nassAPI.downloadUpdate(); st.textContent=r.ok?'Update imepakuliwa. Bonyeza Install Update.':'Hitilafu: '+r.error; }; q('#installUpdate').onclick=()=>window.nassAPI.installUpdate(); window.nassAPI.onUpdateStatus(x=>{ if(x.type==='available') st.textContent='Toleo jipya lipo. Bonyeza Pakua Update.'; if(x.type==='none') st.textContent='Hakuna update mpya.'; if(x.type==='progress') st.textContent='Inapakua: '+Math.round(x.payload.percent)+'%'; if(x.type==='downloaded') st.textContent='Update imepakuliwa. Bonyeza Install Update.'; if(x.type==='error') st.textContent='Hitilafu: '+x.payload; }); }
setupNav(); setupCrud(); setupTop(); setupUpdates(); refreshDashboard();
